### ISSUE TITLE
Email kvitteringerne er forsvundet

### ISSUE THREAD

**Issue by KarenFrederiksen** [os2geo/GEO#11]
![image](https://cloud.githubusercontent.com/assets/4989192/14343368/c857a3e4-fca0-11e5-98cc-3254dc88a96a.png)

Listen over email-kvitteringer er væk. Kvitteringerne bliver dog udsendt ved indberetning til systemet.

**Comment by runetvilum** [comment]
Rettet efter skift til ny couchdb server
