### ISSUE TITLE
Mulighed for at nulstille passwords

### ISSUE THREAD

**Issue by KarenFrederiksen** [os2geo/GEO#2]
Lige nu skal man slette brugeren og oprette brugeren igen for at nulstille password. Det ville være smart med en knap, der udsendte en mail.

**Comment by HasseHauch** [comment]
Kunne være en løsning med en makro som sletter brugeren og opretter en ny på samme mail.  Sikkerheden er at man får en mail med link til at oprette brugeren igen..
