### ISSUE TITLE
Mulighed for at huske login

### ISSUE THREAD

**Issue by KarenFrederiksen** [os2geo/GEO#4]
Jeg har en slutbruger, der skifter mellem to meget lange mailaddresser ved logon: funktionsudbud.aabybro@????.dk og asfaltbestillingnord@????.dk. Han ønsker sig at systemet kan huske de to mailadresser, men også gerne passwords.

**Comment by HasseHauch** [comment]
Det skal lige afklares om det er på OS2geo eller i Appen?
Hvad siger du Karen?

**Comment by kjoller** [comment]
Det er primært i appen, så vidt jeg kan lure.

**Comment by KarenFrederiksen** [comment]
Det vel både og, men i min brugers tilfælde i webapp'en.

**Comment by runetvilum** [comment]
Opdateret samtlige javascript framework.
Nyt link til test
http://geo.os2geo.dk/couchdb/app-d2121ee08caf832b73a160f9ea022ad9/_design/app3/web/index2.html
