### ISSUE TITLE
Massive genudsendelser og manglende udsendelser af mails i bestemte temaer

### ISSUE THREAD

**Issue by kjoller** [os2geo/GEO#7]
Det er sket to søndage i træk: Geo har udsendt mails om indberetninger i et bestemt tema (Først 'Renholdelse', i går 'Skilte' i vores tilfælde). De kommer flere gange pr. indberetning, men ikke nødvendigvis alle.

Det er mellem kl. 15 og kl. 20. d. 25/10-2015 (og ugen før)

I 'Skilte'-tilfældet var der desuden en indberetning kl. 9.57 og dagen før kl. 10.00, der ikke er blevet sendt mail på. Genundsendlserne er dybt irriterende, manglende mails er kritisk!

Kører der en rutine over weekenden (enten hos os eller os cloud-udbyderen) der kan influere på mail-serveren?

**Comment by runetvilum** [comment]
rettet efter skift til ny couchdb server
